import React, { JSX } from "react";
import {
  BedDouble,
  Wifi,
  Tv,
  BathIcon,
  Coffee,
  GlassWater,
  ConciergeBell,
  ShowerHead,
  ShieldCheck,
  Bath,
  Thermometer,
  Scan,
  Waves,
  WavesLadder,
  Building2,
  Armchair,
} from "lucide-react";
import { PiHairDryer } from "react-icons/pi";

export const iconMap: Record<string, () => JSX.Element> = {
  "Büyük Yatak": () => React.createElement(BedDouble, { size: 20 }),
  "İki Tek Kişilik Yatak": () => React.createElement(BedDouble, { size: 20 }),
  "WiFi": () => React.createElement(Wifi, { size: 20 }),
  "Akıllı TV": () => React.createElement(Tv, { size: 20 }),
  "Banyo": () => React.createElement(BathIcon, { size: 20 }),
  "Mini Bar": () => React.createElement(GlassWater, { size: 20 }),
  "Oda Servisi": () => React.createElement(ConciergeBell, { size: 20 }),
  "Saç Kurutma": () => React.createElement(PiHairDryer, { size: 20 }),
  "Duş": () => React.createElement(ShowerHead, { size: 20 }),
  "Kasa": () => React.createElement(ShieldCheck, { size: 20 }),
  "Küvet": () => React.createElement(Bath, { size: 20 }),
  "Klima": () => React.createElement(Thermometer, { size: 20 }),
  "Ayna": () => React.createElement(Scan, { size: 20 }),
  "Jakuzi": () => React.createElement(Waves, { size: 20 }),
  "Havuz": () => React.createElement(WavesLadder, { size: 20 }),
  "Balkon": () => React.createElement(Building2, { size: 20 }),
  "Oturma Grubu": () => React.createElement(Armchair, { size: 20 }),
  "Kahve": () => React.createElement(Coffee, { size: 20 }),
};
